name = "emoga-access"
main = "src/index.js"
compatibility_date = "2024-11-06"

workers_dev = true

preview_urls = false

[vars]
NOTIFY_EMAIL = "abhinav.utkarsh@tum.de"

MAIL_FROM = "EMO-GA Access <noreply@send.abhinavutkarsh.com>"

ALLOWED_ORIGINS = "https://abhinavutkarsh.com,https://www.abhinavutkarsh.com"

PBKDF2_ITERATIONS = "100000"

TOKEN_TTL_SECONDS = "600"

[[r2_buckets]]
binding = "FILES"
bucket_name = "emoga-private"

[[kv_namespaces]]
binding = "RATE"
id = "d9c229a4c1a5404cb50dac52aaf015d1"

[[ratelimits]]
name = "UNLOCK_LIMIT"
namespace_id = "1001"
simple = { limit = 10, period = 60 }

[[ratelimits]]
name = "REQUEST_LIMIT"
namespace_id = "1002"
simple = { limit = 3, period = 60 }
